### ISSUE TITLE
Control the width of UISegmentedControl on FXFormOptionSegmentsCells

### ISSUE THREAD

**Issue by timgcarlson** [nicklockwood/FXForms#291]
I'm using FXFormOptionSegmentsCell for some fields where there is a simple "yes/no" like selection.

![screen shot 2015-01-22 at 3 30 39 pm](https://cloud.githubusercontent.com/assets/3299917/5866991/b5a7336e-a24b-11e4-87ae-49cd757396cd.png)

I want the segmented controls to all be a uniform width. Is there anyway to adjust the width of the segmented controls without having to modify in the FXForms source code? Should I subclass FXFormOptionSegmentsCell?

**Comment by nicklockwood** [comment]
Yeah, subclassing the cell is your best bet here. It should be pretty trivial - just subclass the FXFormsOptionSegmentsCell and override the - (void)layoutSubviews method . You can copy the existing code, but use a hardcoded width.

Then just specify your new cell class in the form field dictionary instead of FXFormOptionSegmentsCell.

**Comment by timgcarlson** [comment]
Excellent, that works brilliantly! I didn't think it would be that trivial, thanks for the help.
