### ISSUE TITLE
strange backgournd color with stepper 

### ISSUE THREAD

**Issue by realcarlos** [nicklockwood/FXForms#424]
![screen shot 2015-11-05 at 4 43 44 pm](https://cloud.githubusercontent.com/assets/13853/10963585/78aefb22-83dc-11e5-98f0-a85eddbc3253.png)

- (NSDictionary *)needPlayersNumField
{
    return @{FXFormFieldKey: @"needNum",
             FXFormFieldTitle: @"number",
             FXFormFieldDefaultValue:@0,
             @"stepper.backgroundColor": [UIColor grayColor],
             FXFormFieldCell: [FXFormStepperCell class]};
    
}

**Comment by nicklockwood** [comment]
I'm not sure what you were expecting `@"stepper.backgroundColor": [UIColor grayColor]` to do, but it looks to me like it's working as expected.

If you were trying to just change the color of the buttons and not the background, that's outside the scope of FXForms since I'm just using the standard control and not doing anything special with it, but here are some ideas:

http://stackoverflow.com/questions/8762512/change-appearance-of-uistepper
