### ISSUE TITLE
please back IOS8 compatibility

### ISSUE THREAD

**Issue by plandem** [nicklockwood/FXForms#433]
right now it only works with ios9, because of: 'cellLayoutMarginsFollowReadableWidth'

**Comment by plandem** [comment]
#426

**Comment by nicklockwood** [comment]
This works fine in version 1.2.14, which was released on Novemeber 2nd. It may be that you need to upgrade your Xcode version.

**Comment by plandem** [comment]
I'm not using Xcode, and how is it connected with method that can't be find? I'm not using iOS9 SDK, so right now i have to roll back to 1.2.13 to use it.

**Comment by nicklockwood** [comment]
@plandem, I was oversimplifying. You don't need to use the latest version of Xcode, but you do need to use the latest iOS SDK.

The reason that FXForms is giving you an error is because you are trying to build using the iOS8 SDK, and the cellLayoutMarginsFollowReadableWidth symbol doesn't exist in that SDK version.

But if you build using the iOS9 SDK instead, but set the deployment target as iOS8 or earlier FXForms will still work fine on iOS8 because it checks for the existence of that feature at runtime.

You don't need to use the iOS8 SDK to support iOS8, but if you choose to do so for some reason, you'll need to either use an old version of FXForms, or modify the new version to compile using the iOS8 SDK.

**Comment by plandem** [comment]
i see. thanks.
