### ISSUE TITLE
Intercept input value and change another field in the form 

### ISSUE THREAD

**Issue by ghost** [nicklockwood/FXForms#72]
Thank you for this great great library it really makes building forms much easier.

Im having a problem with changing a field's options based on the user input in another field. Lets assume I have a list of 3 products: Juice, water, coffee. if the user selects juice or water then he/she can select multiple options for these products at once. If the selected product is however coffee then only one option can be selected (See code below).

I have no idea how to get the select product value and change the options based on that using FXForms. In the documentation you mention KVO and custom setter, but since Im new to IOS development I find it hard to understand without some examples, .

I hope you can give an example on how to intercept input values and update fields based on input :).

typedef NS_ENUM(NSInteger,Product)
{
    Juice = 0,
    water,
    coffee
};

typedef NS_OPTIONS(NSInteger, Options)
{
   Option1 = 1 << 0,
    Option2 = 1 << 1,
    Option3 = 1 << 2
};
@interface ProductSelectionForm : NSObject < FXForm >
@property (nonatomic, assign)Product productList;
@property (nonatomic, assign) Options productOptions;
@end

**Comment by kumargaurav89** [comment]
hi i am using the same approach to show the values. but now i want to show the values from my database instead of hardcoded. so can you please link me with 1 of the best example. and i have several option not 1. which call controller to select 1 value. for example gender and country in your example but you add the options under FormFields.json but in my case i can't specify the values because if can be 5 or 10 or any number.
